Algoritmo "semnome"
// Disciplina: [Lógica de Programação e Java Script]
// Professor: Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Antony Fernando Ribas Rocha Silva
// Data atual  : 03/09/2021
Var
// Seção de Declarações das variáveis 
cont:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para cont de 1 ate 10 passo 1 faca
Escreval("Osasco terror da Oeste")
fimpara



Fimalgoritmo