Algoritmo "lopping2A"
// Disciplina: [Lógica de Programação e Java Script]
// Professor: Jailson
// Descrição: Aqui você descreve o que o programa faz! (função)
// Autor(a): Antony Fernando Ribas Rocha Silva
// Data atual: 01/09/2021
Var
// Seção de Declarações das variáveis 
X, R: inteiro
CONT: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
CONT <- 1
repita
leia (X)
R <- X*3
escreval (R)
CONT <- CONT + 1
ate (CONT > 5)


Fimalgoritmo