Algoritmo "exercico F"
// Disciplina: [Lógica de Programação e JavaScript]
// Professor: Jailson
// Descrição: ;;;
// Autor(a): Antony Fernando Ribas Rocha Silva
// Data atual: 03/09/2021

Var
// Seção de Declarações das variáveis 
cont:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para cont de 1 ate 200 passo 1 faca
se cont mod 4=0 entao
escreval(cont)
fimse
fimpara

Fimalgoritmo