Algoritmo "exercicio E"
// Disciplina: [Lógica de Programação e Java Script]
// Professor: Jailson
// Descrição: Aqui você descreve o que o programa faz! (função)
// Autor(a): Antony Fernando Ribas Rocha Silva
// Data atual: 02/09/2021
Var
// Seção de Declarações das variáveis 
r:real
i,y : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
y<-0
para i de y ate 15 passo 1 faca
r<- 3^y
y<-y+1
escreval(r)
fimpara


Fimalgoritmo