Algoritmo "semnome"
// Disciplina: [Lógica de Programação e Java Script]
// Professor: Jailson
// Descrição: Aqui você descreve o que o programa faz! (função)
// Autor(a):Antony Fernando Ribs Rocha Silva
// Data atual: 01/09/2021
Var
// Seção de Declarações das variáveis 
num1,num2:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
num1 <- 15
repita
num1 <- num1+1
num2 <- num1*num1
escreval (num1," ao quadrado =",num2)
ate (num1 = 200)

Fimalgoritmo