Algoritmo "exercicio a"
// Disciplina: [Lógica de Programação e Java Script]
// Professor: Jailson
// Descrição:
// Autor(a): Antony Fernando Ribas Rocha Silva
// Data atual: 01/09/2021
Var
// Seção de Declarações das variáveis 
i,num:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("escreva um numero de 1 a 10: ")
leia(num)
para i de 0 ate 10 faca
escreva (num,"x",i,"=",i*num)

fimpara

Fimalgoritmo